<a href="https://colab.research.google.com/github/mynamesteenzz-droid/A-File-Versioning-and-Recovery-System/blob/main/air_quality_index_prediction_using_ridge_and_lasso_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

df = pd.read_csv("air_quality_aqi_dataset.csv")
df.head()

        PM2.5        PM10        NO2        SO2        CO         O3    AQI
0   84.187879  138.818745  21.458320  19.119431  1.378817  31.531432  136.4
1   53.889995   86.069525  59.972509   1.261872  0.956577  66.184306  126.1
2   50.069765   73.000712  33.735222  19.244345  0.838730  12.310202   75.1
3   50.070403   62.236643  22.839145  51.941842  1.087409  71.732121  101.4
4  158.795216  292.355968  68.229706  15.692599  0.873410  46.286504  219.2

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df.isnull().sum()

PM2.5    8
PM10     8
NO2      8
SO2      8
CO       8
O3       8
AQI      0
dtype: int64

In [4]:
df.fillna(df.median(numeric_only=True), inplace=True)

In [5]:
df.isnull().sum()

PM2.5    0
PM10     0
NO2      0
SO2      0
CO       0
O3       0
AQI      0
dtype: int64